### ISSUE TITLE
Similar to detach?

### ISSUE THREAD

**Issue by 097115** [oem/lnch#2]
Hi!

Not really an issue, just trying to understand better -- it [seems](https://medium.com/njiuko/using-fzf-instead-of-dmenu-2780d184753f) that `lnch` is somehow similar to [`detach`](http://inglorion.net/software/detach/)? Or am I completely wrong? :)

Thanks!

**Comment by oem** [comment]
No, I think you are right, back when I wrote it I wasn't aware of detach and just quickly through together lnch :)

**Comment by oem** [comment]
Oh I hope it's ok that I closed the issue, we can still use this issue if you have any other questions of course!

**Comment by 097115** [comment]
@oem, 

Sure, no problem, I just wanted to clarify :)

Thanks for your help and for `lnch` :)

**Comment by ppetr** [comment]
Hi, I was reading [your blog post](https://medium.com/njiuko/using-fzf-instead-of-dmenu-2780d184753f) that motivated you to write this tool. I think another standard program to achieve the same could be [`setsid`](https://man7.org/linux/man-pages/man1/setsid.1.html), which not only runs the program in a separate process group, but also in a [separate session](https://stackoverflow.com/q/6548823/1333025).

**Comment by for-coursera** [comment]
Just to add to this collection of alternatives (and for some sort of reference :)), probably [this](https://www.reddit.com/r/commandline/comments/1i8mh2z/i_feel_like_this_should_be_public_knowloge_put_on/) can also act similarly?

    run() { echo "$@" | (nohup ${SHELL:-"/bin/sh"} &) >/dev/null 2>&1; }
